source "http://rubygems.org"

gem "rake"
gem "rails", "3.0.0"
gem "rspec-rails", "2.0.1"
gem "activesupport", "3.0.0"
gem "actionpack", "3.0.0"
gem "activemodel", "3.0.0"
gem "activerecord", "3.0.0"
gem "sqlite3-ruby"
